### ISSUE TITLE
Extensions removed from Chrome store

### ISSUE THREAD

**Issue by ohsusannamarie** [Sjamilla/awesome-recruitment#20]
These extensions have been removed from the Chrome store:
- [Multi-Highlight](https://chrome.google.com/webstore/detail/multi-highlight/pfgfgjlejbbpfmcfjhdmikihihddeeji)
- [Data Saver](https://chrome.google.com/webstore/detail/data-saver/pfmgfdlgomnbgkofeojodiodmgpgmkac)
😢

**Comment by Sjamilla** [comment]
:( thanks for flagging
